# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ff12f7d9df6f44a68360ee089ed8c477f9c1827bcb8cae004b8e1b860de176eb2e9d487226efce4428789de0eb6151f88450e5c4fa49459b8b2ff5cba95f4aa

test:
  secret_key_base: 2258fd9a7537a46ab3e9af1af7e1735a64b7a8871a625f5686887725db4386e5018568441f855654fc405358ad0336a9f66b60ef0e5f4a8055939fafde510968

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
